# .github/workflows/ci.yml

name: Clones Token CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npm run compile
        id: compile
        continue-on-error: false

      - name: Run linter
        run: npm run lint:sol
        id: lint
        continue-on-error: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Slither
        run: pip install slither-analyzer

      - name: Run Slither Security Analysis
        run: npm run security
        id: slither
        continue-on-error: false # Fail the workflow if Slither finds issues
